driver:
  name: docker
  use_sudo: false
  privileged: true
  forward:
    - 11211

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_version: latest
  salt_bootstrap_url: https://bootstrap.saltstack.com
  is_file_root: true
  require_chef: false
  salt_copy_filter:
    - Dockerfile
    - .drone.yml
    - .git
    - .gitignore
    - .kitchen
    - .kitchen.yml
    - Gemfile
    - Gemfile.lock
    - requirements.txt
    - tests
    - .travis.yml
  state_top:
    base:
      '*':
        - memcached
        - memcached.config
        - memcached.python_memcached
  pillars:
    top.sls:
      base:
        '*':
          - memcached
  pillars-from-files:
    memcached.sls: pillar.example
platforms:
  - name: centos
    driver_config:
      run_command: /usr/lib/systemd/systemd
  - name: ubuntu
    driver_config:
      run_command: /lib/systemd/systemd
  - name: debian
    driver_config:
      run_command: /lib/systemd/systemd

suites:
  - name: nitrogen
    provisioner:
      salt_bootstrap_options: -qX -p git -p curl -p sudo git 2017.7
  - name: oxygen
    provisioner:
      salt_bootstrap_options: -qX -p git -p curl -p sudo git 2018.3
  - name: develop
    provisioner:
      salt_bootstrap_options: -qX -p git -p curl -p sudo git develop

verifier:
  name: shell
  remote_exec: false
  command: pytest -v tests/integration/
